package com.example.eightapiwithmysql.model;

import lombok.*;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ToString
@Builder
public class Person {

    private Integer id; //automatically generated by server | FE need not send this
    private String firstName;
    private String lastName;
    private Integer age;
    private  String dob;

}
